[[project]]
name = "La Traque"
desc = "Notre premier jeu. Edité chez Don't Panic Games en mars 2025"
tags = ["La Traque", "Don't Panic Games"]
links = [
    { name = "Voir sur le site web de l'éditeur", url = "https://www.dontpanicgames.com/fr/shop/jeux/la-traque/" },
    # { name = "docs", url = "https://example.com" },
]

[[project]]
name = "ipsum"
desc = "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Praesentium, nisi saepe dolor unde iusto dolore nam, vero optio consequuntur repudiandae et! Atque libero expedita laudantium cupiditate, sit explicabo sequi ipsa!"
tags = ["lorem", "ipsum"]
links = [
    { name = "homepage", url = "https://example.com" },
    { name = "source", url = "https://example.com" },
    { name = "docs", url = "https://example.com" },
]

[[project]]
name = "dolor sit"
desc = "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Praesentium, nisi saepe dolor unde iusto dolore nam, vero optio consequuntur repudiandae et! Atque libero expedita laudantium cupiditate, sit explicabo sequi ipsa!"
tags = ["amet", "ipsum", "vero", "optio"]
links = [{ name = "github", url = "https://example.com" }]

[[project]]
name = "amet"
desc = "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Praesentium, nisi saepe dolor unde iusto dolore nam, vero optio consequuntur repudiandae et! Atque libero expedita laudantium cupiditate, sit explicabo sequi ipsa!"
tags = ["lorem", "ipsum"]
links = [
    { name = "website", url = "https://example.com" },
    { name = "github", url = "https://example.com" },
    { name = "docs", url = "https://example.com" },
    { name = "wiki", url = "https://example.com" },
]

[[project]]
name = "lorem-ipsum"
desc = "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Praesentium, nisi saepe dolor unde iusto dolore nam, vero optio consequuntur repudiandae et! Atque libero expedita laudantium cupiditate, sit explicabo sequi ipsa!"
tags = ["dolor", "lorem", "ipsum", "amet"]
links = [
    { name = "github", url = "https://example.com" },
    { name = "docs", url = "https://example.com" },
]

[[project]]
name = "praesentium"
desc = "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Praesentium, nisi saepe dolor unde iusto dolore nam, vero optio consequuntur repudiandae et! Atque libero expedita laudantium cupiditate, sit explicabo sequi ipsa!"
tags = ["lorem", "ipsum"]
links = [
    { name = "homepage", url = "https://example.com" },
    { name = "github", url = "https://example.com" },
    { name = "docs", url = "https://example.com" },
]
